= 晋南绛县 541

又看到了关于三线建设的新闻，好奇心促使我去寻找关于家乡这段历史的记忆，
以前经常听长辈们讲诉厂里的那些故事，也去过山里几次，刚才找了一下，找到了这篇文章，
感觉不错，比较亲切，与大家分享一下家乡那段历史。
那段不容忘却，也绝不能被青年一代忽略的历史。向祖辈们致敬……
可以说，再过十几年，也许几年，当兵工二代们坚守到最后，
赡养父辈——兵工一代“百年”后，彻底离开 541 时，中条山的青山绿水作证，
这里曾经有个特大型兵工基地，这里曾经有数万兵工战士、家属子女抛洒过青春热血、
为了最初的理想和信念而埋骨他乡！人们辛酸地却亲切地叫她 —— 541。

image::http://mmbiz.qpic.cn/mmbiz/O7d2tzeBGVAtqQCMpiaZicePgzbZ7tmeaQUK6gS7sV7ibFpUhibPMW8zwguljkyFTL4EoMmDsBlzomeH8UF0dGrticw/640?wxfrom=5&wx_lazy=1&wx_co=1[Image]

* 一分指 5409 国营红山机械厂 坦克总装厂
* 二分指 5419 国营红流机械厂 坦克车体炮塔铸件毛坯厂
* 三分指 5439 国营红泉机械厂 坦克零部件锻造毛坯厂
* 四分指 5429 国营红峰机械厂 坦克零部件机加厂
* 五分指 5449 国营红岩机械厂 坦克零部件冲压厂
* 六分指 5432 国营汾水机械厂 发动机毛坯厂（中途改建，改为541总厂科研所和汽车大修厂，84式（WZ-621）坦克架桥车、双37半自动自行火炮底盘、等，均在该厂设计定型。）
* 七分指 5442 国营汾河机械厂 发动机机加厂（中途改建，改为541总厂技工学校）
* 八分指 5452 国营汾南机械厂 发动机泵滤厂（中途下马，厂址移交地方公共安全专家使用）
* 九分指 5437 坦克火炮厂（中途下马，厂址移交地方公共安全专家使用）
* 十分指 5447 国营燎原仪器厂 坦克稳定器厂
* 十一分指 5438 坦克瞄准镜厂 （中途下马，厂址移交地方武警使用）
* 十二分指 5448 坦克夜视器材厂 （中途下马，厂址移交地方武警使用）
* 十三分指 5428 坦克光学仪表厂 （中途下马，厂址移交地方武警使用）
* 十四分指 5433 坦克炮弹总装厂 （中途下马，厂址报废）
* 十五分指 5443 坦克炮弹冲压机加厂 （中途下马，厂址报废）
* 十六分指 5444 坦克炮弹引信厂 （中途下马，厂址移交地方使用）
* 十七分指 自备发电厂
* 十八分指 509 铁路专线指挥调度部

这是一个正在被时代遗忘的地方。
作为曾属于重要军事保密工程的国家第二坦克基地，541 工程散落分布在山西南部的中条山麓。
40 个年头过去了，历史的风沙荡去了昔日的韶华，没有了火红的岁月，也没有了火红的歌。当人们的目光都投向山外的喧嚣时，这里的一切正复归初始的沉寂。　　

——题记

image:http://mmbiz.qpic.cn/mmbiz/O7d2tzeBGVAtqQCMpiaZicePgzbZ7tmeaQzaibu1cjScdzBMz7MHUJjExXg9F0ZluTy2PxKI2eSJs6e4qQQ34cw9g/640?wxfrom=5&wx_lazy=1&wx_co=1[Image]　　

== 楔子

中国的三线建设是党中央、毛泽东制定的一项重要战略决策。
早在 1964 年 5 月，国家计委李富春等向毛主席、党中央汇报第三个五年计划的编制情况时，
毛泽东就提出制订计划要考虑备战，并明确提出：“第三个五年计划，
原计划在二线打圈子，对基础的三线注意不够，现在要补上。“
1964 年 8 月，党中央书记处召开会议，按照毛主席的指示，讨论研究三线建设问题，
会上提出为了准备应付帝国主义可能发动侵略战争，首先集中力量建设三线。

在关于三线建设的战略构想里，毛泽东将全国划分为三类，前线、中间地带和后方，分别称为一线、二线和三线。
三线的范围是乌鞘岭以东，京广铁路以西，雁门关以南，昭关以北地区，包括桂、粤、湘、鄂、豫、晋、青、甘、陕、滇、黔、川 13 个省和自治区。
1969 年中苏珍宝岛战争爆发，中苏关系异常紧张，前苏联领导人曾决定对中国的重点军事工业进行毁灭性核打击，
从积极备战的角度出发，我国上上下下展开了轰轰烈烈的“三线建设”。

为了保证三线建设顺利进行，毛泽东决定对一些重点三线建设基地和工程实行军管，甚至直接派军队去施工。
同时，考虑到战争的威胁已经临近，为了抢时间，他要求三线建设的速度也要加快。
中央根据毛泽东的这个指示，提出了三线建设要与帝、修、反抢时间、争速度的口号。
当时工厂都集中在大城市和沿海地区不利于备战。
要抢时间把沿海有些工厂采取“一分为二”的方法，将其部分设备搬到三线去。
而且搬迁要越快越好。因此，三线建设在结合沿海、沿边企业搬迁的基础上同步大规模展开。

== 第一章 问道天弓铸神剑

珍宝岛是位于黑龙江省乌苏里江主航道中心线中国一侧的一个小岛，面积 0.74 平方公里，历来为中国领土。
中国全国上下大规模的三线建设主要源于发生在乌苏里江珍宝岛上的两国边境冲突。
从 1967 年至 1969 年，前苏联先后入侵珍宝岛 16 次。
中国军人英勇顽强，用血肉之躯抵挡了苏联坦克、装甲车的侵略。
为了用军事施压，前苏联紧急向中苏边界调运了大批军队，
因只有一条西伯利亚铁路作为运输干线，该线在 1969 年夏天竟一度停止客运只供军运。

蒙古虽然不是由前苏联控制和操纵的华沙条约组织的缔约国，但前苏联通过苏蒙双边军事条约、早已把蒙古变成他的东方军事基地。
第二次世界大战后，蒙古境内原来就驻有苏联的军队，后来撤离回国，只留下少数通讯兵和空军技术人。
二十世纪六十年代起，随着中苏关系的紧张，大量的前苏联军队从欧洲调往蒙古。
一时间，中蒙边界上军队密布，战云骤起，战争大有一触即发之势。

中国大规模工业化的起步是在建国以后，其标志是“一五”时期以前苏联援建的“156 项”建设为中心的经济建设，它是中国工业化的奠基石与里程碑。
位于内蒙古包头市青山区的 617 厂便是国家“156 个重点建设项目之一。
珍宝岛战役的爆发后，由于包头距离中蒙边境非常近，使得作为国家第一坦克生产基地的包头 617 厂直接受到战争威胁。
为此，中央决定在山西南部的中条山山区建立国家第二坦克生产基地，代号为 541工程。

中条山战略地位非常重要，抗日战争时期著名的“中条山战役”就发生在这里。
被日方称之为“中原会战”的中条山战役，是抗日战争进入相持阶段后，正面战场国民党军队在山西范围内的惟一一场大规模对日作战。
战役前后历时一个多月，最后以中国军队的大规模溃败而告终。
中条山与太行、吕梁、太岳三山互为犄角，它屏蔽着洛阳、潼关和中原大地，拱卫着西安和大西北，瞰视着晋南和豫北。
541 工程作为国家第二坦克基地建于此，可以为巩固华北和守卫西北提供武器装备上的重要支撑。

541 工程建设规模非常之大。工程的初期计划有一个总装厂、一个车体炮塔铸造厂、三个坦克机械零件加工厂、两个坦克炮厂、三个 580 马力坦克发动机厂、三个炮弹厂、三个光学仪表厂、一个橡胶厂、发电厂、大型职工医院、铁路专线运输指挥部等。
工程计划所建设的十八个分厂，依次称为第一分指挥部，第二分指挥部，第三分指挥部等。
最北面的三分指位于临汾地区的翼城县境内，其余十几个分指全部位于运城地区，
其中四分指、十七分指、一分指、二分指、五分指、十八分指、九分指位于绛县境内；
六分指、七分指、八分指、十分指位于闻喜县境内；
十一分指、十二分指、十三分指、十四分指、十五分指、十六分指位于夏县境内；
541 总部设在闻喜县的东镇。

541 工程由解放军第28军援建，建立时直属当年的解放军装甲兵司令部，后归属第五机械工业部。
在“靠山、分散、隐蔽”方针的指导下，各个分指分布在中条山下的临汾、运城两个地区，星罗棋布地绵延于绛县、闻喜、夏县、翼城境内 130 公里的地域。
541 十几个分指计划生产的是当年很有技术含量的 WZ-122 型中型坦克，后改为 59 式改型和 84 式架桥坦克。

根据中央军委常规兵器工业领导小组的指示，541 工程分三批建设，用两年半时间全部建成。
从 1970 年 4 月开始到 1973 年 7 月，是 541 工程建设的时期，各专业厂基建初具规模，
部分厂的生活区也已建成，贯穿各专业厂的公路、铁路专用线也建成通车。
由于是国家重点大型三线建设工程，山西南部几十个县都组织民兵和民工参加 541 工程建设，
在穿着草绿军装的军人组织和带领下，他们以连为单位，在中条山里各个分指的厂区和家属区垒护坡、拉土方，在铁路建设工地上抗枕木、铺钢轨。
当然，各个分指的核心工程是不让民工干的，保密车间的建设及设备安装都是由解放军工程兵负责的。
当时插队到山西南部农村的好多知青也参加了 541 工程建设会战。
直到今天，北京知青论坛网上，许多当年的知青都在网上寻找当年的战友和回忆那些曾经燃烧的青春岁月。

== 第二章 好人好马上三线

”兵工战士是块砖，哪里需要哪里搬“。为了建设 541 工程，全国各大中城市企业的工程技术人员，大中专毕业生，部队整建制的复转军人，留苏工程技术骨干，我国第一代坦克技术专家，纷纷从祖国的四面八方来到人烟稀少、遍地荒凉的中条山。
这其中，由于 541 是包头 617 厂的后备厂，所以技术工人主体主要是来自包头的兵工战士。
他们是新中国第一代产业工人，是最富责任感的主人翁。毛主席说，三线建不好他睡不好觉。
为了让他老人家放心，建设三线是成为他们义不容辞的责任。
他们有着一个共同的渴望、共同的梦想，那就是建设江山，保卫江山。

541 工程各分指选址大多是中条山中的荒山土垣，很多地方没有地理标志，也没有地名。
1970 年的冬天，二分指也就是 5419 厂开工建设时，一批批戴着眼镜的工程师，一群群穿着的工人，从五湖四海来到绛县卫庄一个不知名的地方安营扎寨。
生活安顿下来后，给家里人写信时却说不上这是啥地方，于是出门去问在地里干活的当地老农。
老农停下手上的活计，指着周边的几个村子说，这里离里册村二里半；离下村二里半；离卫庄二里半，此地正好居中，就叫个“二里半”吧！

各个分指的厂区都是沿山沟展开，分家属区和车间两部分。
车间一般人是不让进的，清一色的水泥红砖大车间，一座挨着一座沿着山沟的河滩逶迤展开。
厂区被高密度树林覆盖着，站在山顶上几乎看不到几座房子。
厂里有自己的服务体系，邮政专属的信箱、幼儿园、学校、商店、医院等等。

三线建设本着先生产后生活的原则，所以来的早的人由于生活区的楼房和学校都没有竣工，大都安排在附近的农村居住，孩子们也都在农村的学校上学。
后来随着各分指的生活区以及学校纷纷建成，人们就都搬到了厂里。
由于 541 各厂的人来自祖国的四面八方，东北的、北京的、上海的、山东的、河南、河北的、湖南、湖北的、江浙的、陕西的、山西的、四川的、云南的……
基本上各个省的人都有，大家交流起来南腔北调的，所以就基本上改说普通话了。

每天早上六点整，山谷中各个分指的家属区和厂区区的大喇叭就开始广播了。
早上6点半是中央人民广播电台新闻和报纸摘要节目，之后是本厂新闻，然后是音乐节目，
"东方红"、“社会主义好”、“打靶归来“等至今人们都耳熟能详。
八点整，工人么开始上班了，这时喇叭里会吹响集合号，由于是各个分指同时吹，
所以嘹亮的军号的声会从这个山谷响到那个山谷，真可谓是此起彼伏。

541 各专业厂拥有职工人数不等，每个厂基本上职工人数在一到两千人，十多个厂中数四分指工厂规模最大、工人数最多，拥有职工 3000 多人，连家属加起来上万人。
四分指建设选址在续鲁峪里面，基建已经开始，连铁路都通进山里了。
有一位将军来视察时，坐着吉普车顺续鲁河滩一路颠簸着往山里开。
也许是太难受了，将军下车小便了一下，看了看四周的穷山恶水，遂指点说不用往里去了，就建在这儿吧！
于是四分指就紧挨河滩建在了续鲁峪沟口外，旁边紧挨续鲁村，成为 541 各厂选址应该说最好的厂。
四分指人说起来现在还在感谢那位将军。

1973 年下半年开始，541 工程进入调整缓建时期。
由于中苏关系的缓和以及国际形势的变化，国家开始对三线建设的政策进行调整。
541 工程也先后经历了始建、缓建、缩小规模再建等几个阶段。
到 1979 年底，除位于闻喜、绛县、翼城的近十个专业主产品厂建成投产外，
其他部分专业厂如八分指、九分指、十一分指、十二分指、十三分指、十四分指、十五分指、十六分指纷纷下马，
人员和设备也并到了 541 其他厂。六分指改成 541 科研设计院、七分指成为了 541 技校。
虽然 541 规模在缩小，将近一半的项目在下马，但由于整个 541 工程异常庞大，所以整体感觉上还是充满生机的。

和晋南的 541 一样，位于山西北部宁武县的管涔山区，由于独特的地理位置和地形条件，曾被划为北京市的战略后方基地。
1965 年 12 月，党中央华北局、北京市、第五机械工业部组成联合建厂组，在华北地区选择高炮厂址。
经勘察，最后确定 3 个项目建在宁武县的芦芽山区，由北京市负责建设和管理。
1966 年 6 月破土动工，到 1969 年底，3 个厂陆续建成投产。
1981年，宁武山里的国营长城机械厂（代号187）、国营恒光机械厂（代号286）、国营烽火机械厂（代号287）三个生产火炮的军工厂撤销。
三个厂的三千多职工连家属共万人和设备一起被541接收，这应该是541第二次大规模进人。

从 1981 年开始，山西同浦铁路以及现在的大运公路，火车、汽车开始不停地转运设备和人员，
全部搬迁直至 1986 年才基本结束。541 工程自此，虽然处于三线紧缩的大形势下，但却是最为兵强马壮的时候。
七十年代末，军事试制工艺定型后，由于部分项目下马，541 作为坦克整体生产能力没有形成，
生产体系被肢解的支离破碎，所以只能生产部分坦克配件。
但时值中越自卫反击战和两伊战争，541 军品订单还是满不错的，军工战士的自身价值也在火热的工作和勇于攻坚的集体荣誉中得以充分的体现。

== 第三章 大山地标话分指

分指一词在山西南部的各县市是 541 各厂的专属名词。
541 各厂除拥有十几个分指的内部叫法，以及 5409 厂、5419 厂、5429 厂等番号外，
由于创建于火红的岁月，各厂都有一个以红字打头的对外名称，诸如红山机械厂、红流机械厂、红峰机械厂等。
军转民之后各个分厂的名字开始以山西冲压厂、华晋机械厂、晋南机械厂等各五花八门的形式出现。
但不管风雨如何变化，分指一词始终被人们流传了下来，并成为中条山各沟里工厂独特的地理坐标。

上世纪八十年代以前，晋南各县市的公交车很少，而且也不往山里的各分指开。
各分指除了有自己的大轿子车每天开往侯马、运城等地外，地处闻喜县东镇的 541 总部每天还专门有一趟班车发往处于群山环抱中的各个分指。
每天总部班车从群山中的这条沟出来，然后再进另一条沟。虽说是山里的企业班车，但服务的素质却一点不比大城市的差，因为他们本身就来自于城市。
当班车到达二里半的二分指时，售票员就会用标准的普通话说到，二分指到了，请下车。
当班车爬上一座山再下到沟里时，售票员就会说到，一分指到了。
坐班车的基本都是各分指的职工，地方的老百姓通常是不能坐的。
山西南部无论城乡都说着一口说山西不山西、说河南不河南、说陕西不陕西的晦涩方言。
这个地方处于晋、豫、三省交接地带，所以语言呈地区方言的过渡性。
县城里的人对普通话还有个认可，山里就不行了，他们索性把分指说的普通话称为洋话，大概象现在人听英语似的。
个别地方人跟分指的人学了几句四不像的普通话，地方上的人便会揶揄地说到，”你别同我分指啊！“

当晋南各县市还都是平房时，地处山里的各分指都已经都是清一色的三层楼房了，而且用的是县城里直到三十年以后才用上抽水马桶。
当地方的县委书记们还在寒冷冬日的平房里烧铁炉子时，山里分指里的职工们家里都已经暖气融融，厂区里高大宽敞的厂房更是热气腾腾。
分指里所有的职工水电不用花钱，而且享受免费医疗，就连家属也可以享受半费医疗。
各分指的都有自己的医院，东镇还有还有 541 总医院，厂里的职工生病，单位会安排职工陪顾。

中条山一带民风淳朴，上世纪一百年，除 1941 年抗日战争时期中条山战役时，这里来过大批的日本兵、国民党军、川军、晋绥军和八路军外，就属这次 541 工程建设来的多了。
连职工带家属十几万人，住到了大山的各个山谷中，只不过盖起的不是炮楼，而是比炮楼大得多的苏式厂房。
所有的地方人包括山民及县城里的市民都对分指充满了好奇。
各分指的铁路建成通车时，山里的老百姓扶老携幼，成群成伙地来看火车。”这么大的家伙，趴着都跑得这么快，立起来就跑得更快了。“
这句话无从考证出处，也不知道是真是假，但却是当时分指人用来形容老百姓没见过火车的口头禅。

位于翼城县庄里村附近的三分指，是搞锻造生产的。据说厂里的大锻锤，打一下就相当于一次3、4级地震。
当年全国只有三台。一台在上海造船厂，生产船用曲轴，另两台就在 541，用于锻造坦克大轴的。
为减少对人的震动，大锻锤有3、4层楼高，他们发的劳保鞋也是带簧片的。
后来厂里开运动会赛跑时，庄里村的老百姓夸分指里的人跑得快，村里见多识广的明白人就说了，”知道吗？他们的鞋里有弹簧呢！“

山西的老百姓那时是不吃鱼的，也不要知道鱼怎么吃。分指的职工们星期天休息时会三三两两骑着自行车去附近的水库钓鱼。
附近的乡镇赶集时，厂里的人也会到集市上买东西。
541 建厂之前一块钱能买到二十二个鸡蛋，大批的工人来到山里后，一块钱也能买到十七、八个鸡蛋，大公鸡几块钱就能买到一只。
每当赶集回来，工人们骑着自行车，或车把上吊着四、五只鸡，或带着一筐鸡蛋。

分指里工人的工资不是很高，基本上也就是五、六十块钱，但由于住房、水电、教育、医疗全部免费，加上那时候物价超低且相当稳定，一个职工养活一家四、五口人是富富有余。
粮食按工种供应，从二十八斤到三十二斤不等，干部低，工人高，每斤不到一毛钱。
食油每人半斤，现在看是少了些，但是那时以粮为纲，不可能有更多的地去种油菜、花生。
肉属于副食，每斤七毛六分钱，凭票供应，确保每个人每月都能吃到肉，而不是部分人吃肉。

由于分指的人大都来自大中城市，所以不论从生活各方面都在地方上领风气之先。
县城里的人没有见过带裤线的裤子，当 541 的职工到各个县城办事，他们才发现裤子还有这样的穿。
令他们感到困惑的是不知道裤子上的线是怎么弄上去的。
分指家属区的街道，路灯明亮，水泥马路很平，从改革开放兴起了高跟鞋，分指的女人们就昂首挺胸地穿了起来，而这时候县城里都还连个像样的街道都没有呢。
即便是现在的侯马市，那时候全市连附近农村的人口加起来才十几万，就铁路西面有条老街，窄窄的街道，低矮的平房，十字路口有个商店和饭店。
就这么个地方，据说八国联军进北京的时候，慈溪太后亡命山西时还在路西的小巷那住过呢！
但侯马市彭真的老家倒是真的，至今侯马火车站的大牌匾上还有彭真的题字，落款写着傅彭真。
八十年代初，当侯马的街上开始有星星落落的楼房出现时，位于市中心火车站前两百米新田路的晋机招待所，就是 541 四分指驻侯马的派出机构。
四层高的建筑，二楼宽大的阳台，曾让不少路人驻足，同时也成为那一时期侯马的地标性建筑。

闻喜县东镇是位于南同浦铁路上的一个小镇，地方虽然不大，却是一个非常重要的军事要地。
不大个镇子除 541 厂总部、541 厂总医院外，还有解放军总后勤部 2395 医院、214 地质队、解放军 3534、3531 军服厂、2304 仓库等。
虽说是个镇，可其占地规模可远比几十里外的闻喜县城还大。
南同浦铁路穿镇而过，有个小小的火车站。
七十年代时，由于这里的军事单位较多且级别较高，许多过往的客车都会在这里停。

地方上的人们管东镇叫东镇，分指的人们却叫东镇为总部，他们已经把那个镇子忽略掉了。
因为这虽然是个镇子，却是各县委书记，包括地委书记都要经常因土地和民工问题前来请示和汇报的地方，省里的领导有时一来也经常是半个月。
541 工程总部作为分散在大山里各分指的指挥中心，地位和作用非常显著，也让人感到异常的神秘。
每当召开各分指工作会议时，总部大院办公楼的前面就会整齐停放几十辆崭新的草绿色军用吉普车。
另外，还有很多灰色和黑色的华沙和伏尔加小轿车，其阵势仿佛兵团司令部开作战会议一样。

image:http://mmbiz.qpic.cn/mmbiz/O7d2tzeBGVAtqQCMpiaZicePgzbZ7tmeaQOic4334RgQPQb168IO7WfLKBgRP6M5zgsw9kloNDAMQQpMibHIoib20ZQ/640?wxfrom=5&wx_lazy=1&wx_co=1[Image]

== 第四章 记得纯真少年时

有生活就有孩子们，大山里的三线也一样。大山里一座座幼儿园荡漾着孩子们的歌声，一座座学校里也不时传出朗朗的读书声。
他们大多在童年的时候，就告别都市，跟随父母来到三线，属于兵工战士献子孙的被献掉的那一代。
虽然如此，但是，他们的童年是快乐的，他们的童年是幸福的，因为他们生活在伟大的毛泽东时代。

学校开学时，黑板上会写到，”报到交学费一元，家庭困难的请家长开车间证明免费。”
开学后，孩子们不仅要学习功课，还要组织学毛选学习小组，还要参加批邓反击右倾翻案风批判会。
老师时不时对学生进行家访，与家长共同关心学生的进步。
如果那个同学因生病耽误了课，老师会对学生单独进行补课。
另外，学校还经常组织学工、学农、学军活动，到工厂和父辈们一起劳动，到农村帮助农民割麦子，在学校的操场上在民兵的带领下练习刺杀。

节日时，孩子们会穿上白衬衣、蓝裤子、纯白网球鞋，佩戴上红领巾，兴高采烈地以运动会或歌咏比赛的形式欢庆自己的节日。
这一天，有的家长也许会给孩子两角或者五角钱，两角钱在那时候可以买很多的东西，一根冰棍才三分钱，一个作业本才一毛钱。
当然了，那时候没有肯德基，孩子们也没有太多的消费。
更多的是，孩子们会把这钱自己存起来，存到足够多时交给家长，或者在同学有需要帮助同学。
比如，有的孩子转笔刀丢了没敢跟家长说，他会主动买一个送给同学。
那时候几乎所有的孩子都有一个标志，那就是胸前都挂有一把家门的钥匙，因为父母上班后，每个孩子都是家里的小大人。

生活在大山里的孩子们，可以感受着城市里没有的四季季节变迁：春天有漫山遍野的野花绿草；夏天有一眼望不到边的谷穗麦田；秋天有缤纷飘舞的漫天黄叶；冬天有白雪皑皑的高山丘陵。
而每个季节，孩子们都会生发出一些玩法。
春天一大群小孩满山跑着吹柳哨、编草帽玩打仗的，夏天在麦地的田埂下烧卖穗吃，秋天摘酸枣，或偷挖过农民的红薯烤着吃，冬天雪地里用马尾套鸟。

放学后，男孩们通常是三五成群地在家属区的马路上滚铁环、打弹弓、赢烟盒、摔方宝。
女孩们则凑在一块在楼前跳皮筋、丢沙包、踢毽子。岁数稍大点的孩子对这些不屑一顾，认为是小儿科。
受战争电影的影响，他们已经开始模仿父辈，并从他们的身上寻求榜样的力量了。
有一次，四分指的几个初中的孩子竟然趁卡车司机不注意，把一辆大解放开走了。
他们开出了大山，一直开到了几十公里外的曲沃县城。当然了，晚上回来每个孩子都免不了挨一顿臭揍。

露天电影可以说是每一个孩子记忆最深刻的事情。
孩子们之间总会有一些准确的内部消息，所以一般放学的时候孩子们基本都知道今天放啥片子。
每天下午四点一放学，孩子们就会三三两两搬上板凳去占地方。
晚上大山里一片寂静，只有家属区的的银幕前人头攒动。那时候电影很少，看电影是最主要的娱乐了。
影片除国产的以外，进口片大多来自社会主义阵营的国家，因此有这样的一个顺口溜：朝鲜电影有哭又笑，阿尔巴尼亚电影又搂又抱，罗马尼亚电影莫名其妙，越南电影飞机大炮，中国电影新闻简报。
有时候放一部好片子，因为几个分指要同时放，所以厂里工会专门有车负责倒片子。经常演了了一盘片子，大家就都在操场等，有一回一部电影竟然放了一个晚上才演完。
后来，各厂都建起了自己的工人俱乐部，露天电影也从此成为了历史。

七十年代，唐山大地震过后，全国好像到处都要地震了，541 各分指都成立了地震办公室，负责监控地震。
厂里给每家每户在家属区的空地里都盖了地震蓬。
人们在茶余饭后谈得最多的就是地震，记得当时推广预感地震的方法很多，什么地震前猫狗反常，耗子搬家，什么动物园的动物都不睡觉，什么下雨闪蓝光，睡觉前要把酒瓶子倒过来放，看看灯晃不晃。
有一回一头猪把一个分指里的地震监控设备的线拱了一下，地震仪器显示异常，厂里拉响了警报。
全分指的人都跑到了操场，连附近村里的老百姓也扶老携幼跑到麦地里避震。

孩子们似乎不像大人们那么紧张。大山里没有什么热闹，一闹地震，人们全跑到操场的空地上，也让孩子们感到非常惊奇。
吃的、喝的、穿的、用的全从家拿出来了，孩子们虽然不敢大声说话，但看着一群一群的人，也觉得很有意思。
白天不闹地震了，一放学孩子们就三三两两地串地震蓬，玩打仗的。那时候的孩子没有忧虑，不用上补习班，也不用去学电子琴。
他们的理想就象小时候的作文一样，长大了要当解放军。

== 第五章 保军转民大转型

八十年代初，541 各分指开始实行保军转民的战略性调整。
作为国内具有强大机械加工能力的大型兵工企业，541 在国家的支持下，1980 年，下属的四分指最早开发了 541 人引以自豪的130轻型卡车，到上世纪80年代末，又开发系列旅行客车。
一时间大江南北到处跑的都是 541 的“华丰”面包车。
其他各分指也都根据自己的情况开发出不少民用产品，比如十分指生产的“美猴王”电动游览车曾是我国生产的第一台电动高尔夫球车。

那个时候也是 541 各厂效益最好的时候。各分指的车间都在加班干活，到点不回家的，
单位就会从食堂给每个人打回来加班饭。虽然工作任务很紧，但工厂对员工却是十分关心的。
工会和团委把每个没结婚青工的生日登记好，到生日那天专门做生日饭。
而吃完了生日饭的八十年代新一辈们，更是满腔热情地投入到生产的大会战中。
”大干红五月”、”奋战一百天”等活动成为那时候人们的精神风貌。

厂里的效益好，职工的福利也高。每到秋天，厂里就会用专列从东北拉大米，分给职工。
这时候，厂区的发货站台上，机车冒着蒸汽，忙碌的人们把一麻袋一麻袋的大米搬下来，
然后分到各车间名下。全厂职工家属把家里能装米的家伙式都拿来了，在各单位等着分大米。
大家兴高采烈的，场面跟过节一样。

虽然改成民品生产了，但每天上班吹军号还是一如既往。
以前做军品时外地来分指办事的人少，改成民品生产后，
全国各地来的供货商以及买产品的客户不断地来到山里。
他们一方面为大山中的541工程奇迹感到震撼，同时也对军工技术生产的产品万分信赖，
更对生活、工作于大山里的职工产生敬佩之情。

实行工资改革后，职工的工资直线上涨，青年职工结婚已经由木制家具的多少条腿过度发展到组合柜、电视、洗衣机，并且开始流行旅行结婚。
大批的大、中专生也陆续来到了厂里，厂里的单身宿舍不仅是新鲜血液的象征，同时也成立一道风景线。
当然，他们不是象建厂时的军工战士怀着责任来到山里的，而是被这里稳定的工作和优厚的物质待遇所吸引。
后来，在干部“年轻化、知识化”的精神指引下，这些人很快成为了各个厂处室、及车间的各级干部。

541 以其实力和口碑很快引起了全国各地的关注，其时，正值沿海城市开放。
山东、江苏、浙江一些城市急于发展经济，却缺乏支柱性产业，纷纷来 541 考察，希望 541 能够搬迁过去。
但是 541 一些专业厂类似电厂、铸造厂、锻造厂等都是一次性建设，能够搬迁的只是具有机械加工能力的部分厂子，还要互相配套。
所以一波又一波考察的来了，又一波接一波恋恋不舍地走了。
后来当外国的资本开始大批投向中国沿海时，再也没有人来考察、商讨 541 搬迁的事情了。
但是，不管有没有人来关注，541 军工制造已经成为其搏击市场大潮的利器。

== 第六章 脱离兵工序列

1979 年 1 月，当时的国家领导人邓约见工商界和民主党派人士。
座谈时，邓希望荣毅仁等能围绕改革开放做一些实际工作，发挥自己的作用。
在其他人士向邓提出要“摘除资产阶段帽子”时，荣毅仁却提出了吸资兴办实业的建议，并获得邓的首肯。
一个月后，荣毅仁向中央提出了《建议设立国际投资信托公司的一些初步意见》。
当年 6 月，国务院正式批准成立中国国际信托投资公司。10 月，中信公司正式成立，荣毅仁任董事长兼总经理。

1988 年，在国务院的部署下，远在山西晋南中条山的 541 由国家兵器工业部划给了中信公司。
中信公司董事长荣毅仁以满腔的热情接过了 541，从此，541 就把自己十几万职工家属的命运交到了这位“红色资本家”的手里。
541 划给中信，国内官方没有做公开报道，倒是远在大洋彼岸的“美国之音”对此做了报道。
前苏联也都知道了，曾经为应对修正主义侵略的华北某坦克基地已经移交给中信公司。
1991 年苏联宣布解体。541 作为当时应对前苏联侵略的军工基地确实没有必要存在了，
走向市场，发展民品已经成为 541 唯一的出路了。至此，541 正式更名为中信机电制造公司。

中信机电制造公司成为中信集团公司的全资子公司后，1992 年经国务院批准为特大型工业企业。
下辖总装、冶金铸造、锻造、冲压、机加、液压电器、发电等7个专业生产厂和科研设计院、铁路运输公司、职工总医院、技工学校等5个直属单位。
固定资产原值16.5亿元人民币。几十年来，即便按人民币贬值十倍计，固定资产原值起码也相当于现在的 165 亿。

荣毅仁曾说过：”我最大的收获，就是国家把 541 给了我“，当然此话无从考证。
1993 年 3 月，荣毅仁当选为中华人民共和国副主席，同时把中信集团公司的大权交给了王军。
王军是原国家副主席王震的长子，荣毅仁成为国家副主席后，王军被提为中信投资公司的总经理。

541 划归中信后，彻底地脱离了国家的军工序列，除了兵器总公司委托加工的部分军品外，开始大部分以民品为主了。
541 最北面位居翼城县的三分指开始涉猎汽车、煤矿机械、工程机械、农机备件等行业，
以向济南中国重汽供应 651、150、162 黄河前轴为标志，在国内首创 16M 锻锤整体锻造汽车前轴梁，拉开了三分指民品生产序幕。
四分指由晋南机械厂又更名为中信机电车桥有限责任公司，专业生产重型汽车车桥、轻型客车车桥、重型汽车离合器和系列汽车扭杆弹簧，给国内汽车厂家配套。

二分指是一个综合的冶金铸造厂，其强大的冶铸能力在国内都屈指可数。
美国一个公司拿出一亿多美元，承包了二分指的一个车间，搞起了国际铸造，并插上了星条旗。
为了让老美能享受到开发区的政策，山西省还专门将二分指附近划为省级开发区。
五分指因当时是华北地区冲压能力最强的企业，拥有山西省最大、最先进的 1000 吨日本进口冲床，而被命名为山西冲压厂。

位于么里沟的一分指工厂在满足履带式军用车辆生产的同时，坚持军民结合发展的战略，积极发展民用产品，也已形成多种系列。
就连 541 电厂也开发出水泥、砌块、电解铝、板式家具、建筑安装等许多民品项目。
作为负责 541 铁路运输的 18 分指，由于铁路利用率低，绛县以南的铁路全部拆除，
只剩下北面连接几个分指的几十公里铁路，机关也全部从绛县搬迁到了四分指与三分指之间的张村火车站。
由于当时硅铁价格看涨，18 分指也建起了高炉，开始炼硅铁。

541 有人、有设备，人是全国产业工人第一流的，设备也是全国当时最先进的。
从事民品生产，541 别的不缺，就缺流动资金。
而中信公司主要业务集中在金融、实业和其它服务业领域，钱是不缺的。
划归中信后，541 几乎所有的人都认为是选对了婆家，况且婆家还是中央选的。
541 作为半军事化兵工单位，听党的话，跟党走，是他们的一贯作风。
更名为中信机电制造公司后的541各分指摩拳擦掌，
准备在市场经济的大潮中以军工技术再展军工英姿。

image::http://mmbiz.qpic.cn/mmbiz/O7d2tzeBGVAtqQCMpiaZicePgzbZ7tmeaQK5U3rNw9RWv6EDiblHjc3ias8w3fJTfIRmnGeDepwgnfiaYeoSeJmJuLg/640?wxfrom=5&wx_lazy=1&wx_co=1[Image]

== 第七章 军工基地全线失守

1986 年 9 月国家颁布了《全民所有制工业企业厂长工作条例》，把国有企业的领导体制，由原来的党委委集体领导下的厂长负责制，改为厂长负责制。
并在 1988 年 4 月颁布的《中华人民共和国全民所有制工业企业法》中以法律形式固定下来。
规定“企业建立以厂长为首的生产经营管理系统，厂长在企业中处于中心地位，对企业的精神文明建设和物质文明建设负有全面责任。”

脱离军工序列前， 541 各厂在制度创新方面也做了些改革，但步子不大，因为毕竟是多年的老厂、大厂，且企业资产是国家的，没有人愿真正推动，即便改，也要充分考虑职工的利益。
划归中信后，在建立法人治理结构的大旗鼓噪下，541 各分指的厂长迅速开始“人、财、物”大权独揽，一手遮天，用人一人定，签字一支笔，决策一言堂。
企业管理层由厂长组阁，谁当企业党委书记，谁当副厂长，谁当工会主席，均由厂长说了算，党委、工会、职代会形同虚设。
最终党委书记、工会主席、副厂长都成了厂长利益集团的人。
厂长负责制变成了个人专制，党群组织、工会成了摆设，工人阶级的主人翁地位和话语权被剥夺，兵工战士的自豪感、荣誉感至此彻底丧失。

市场经济变化莫测，由于 541 各分指领导决策连连失误，所以一个个分指被迅速搞跨，广大职工生活变得异常窘迫。
最先陷入困境的是一分指，开始在 541 历史上破天荒地拖欠工资。
这股风很快就开始在 541 各厂蔓延开来，有的分指半年甚至一年不给职工发工资。
时间长了，各分指职工对开工资的时间都开始有大概估摸了，那就是五一、国庆、元旦、过年开工资，其他时候是没准的。
职工工资不但发放不及时，近几年虽有所好转，但工资仍然非常低，普通职工大多五六百不到一千，不知道这样的企业，目前全国还能找到几家？
工资可以低，可以发放不及时，可职工家属看病呢？孩子上学呢？没有哪家医院、学校会让你赊欠！
职工家庭因看病、孩子上学致贫的比比皆是；第一代老军工战士，现在大多七十多岁了，得了大病基本上都放弃治疗，默默在家耗尽自己最后的精血；
中国自古有叶落归根、入土为安的习俗，可这些老军工早年来自全国各地，背井离乡、携妻带子，家乡早已没了他们的土地、户口，
唯一的归宿，就是绛县专为这些企业设立的殡仪馆，蜷缩在方寸间，仰望久别的故乡和亲人……

一分指由于长达一年多时间不发工资，一年当中，竟然有 18 人前后因为缺钱养家而自杀。
有一个职工为了养活妻儿，去偷农民喂猪的麸子当口粮吃，当农民跟踪要将其治偷窃罪时，才发现人家一家老小竟然以此为食，不禁也当场落泪。
但是就是这样，厂里朴实的工人还是每天到点上班。
位于翼城县山里的三分指，一个女职工因无法尽到母亲的责任，给他的孩子以温饱的生活，悄然上吊自尽。
其他分指因无法生活下去，上吊、喝药自杀的人也大有人在。
人们天天听到的都是今天这个分指死了几个，明天那个分指又死了几个；五分指有个职工，为了挣点钱补贴家用，帮当地老百姓在树上摘山楂果，结果不小心从树上掉下，摔成残废，至今靠轮椅度日。

在国企改革的旗号下，国有财产开始大量流失，逐步向经营者手中转移。
进材料吃回扣，价值百万的设备几万就卖出去，任用干部大肆收礼。
早在九十年代中期， 541 某分指领导的夫人在参加同学聚会时，就大言不惭地说有五百万工资存款。
工资改革已经进行了无数遍了。然而一遍又一遍的改革，领导的工资越改越高，职工的工资越改越低，且不能按时发放。
每月几百元的工资虽然比七十年代的几十元上涨了不少，但是面对的是物价的全面上涨。
虽说是在山里，物价却一点不低，甚至比当地县城里还贵。也正是因为在山里，才监管缺失。

各个厂的领导都很忙，他们一天又是出国考察，又是国内到处开会。
他们顺应市场经济的发展，想办法千方百计地把厂里的设备倒腾出去，在外面开起自己的工厂。
他们出着差，拿着补助，一方面给工厂找活，一方面给自己找活。
由于厂里的客户和他自己的客户都是一个，所以他那生产的产品不合格的退到了厂里，厂里合格的算他的。
厂里的货款可以不要，但他的货款绝对不会拖欠。
各厂下面的车间，以二级开发的名义公开将厂里的物资拉到厂外卖了，几个领导共同分账。

有的分指的领导为了追求产值，获取政绩，责令车间加班加点干活，加工出的产品被源源不断地拉几千里之外的客户厂家。
由于超计划供货，对方厂家拒绝接收，不得已还得自己在人家那租库房存放。
年底产值一统计产值是上去了，可是过完年产品就又从外地拉回来了，说是退回返修。
产值有了，一统计多少个亿，可是货款没有，工人干了白干，一分钱工资都领不到。

有的分指的中层干部把一个原本好端端的单位搞跨了，年底竟然被评为公司级先进。
换到另外一个单位，用不了几年又把一个单位彻底搞垮，结果竟然成为省级劳模。
也难怪，把一个单位搞好不容易，也很难捞着钱，而把一个单位搞垮太容易了，只有捞到了钱，他才能给上级领导送。
上级领导只要得了好处，工人们能不能生活下去他是不在意的。
借口有的是，市场经济嘛！而且，在 541 能把一个单位搞好是不正常的，搞不好是再正常不过的事情了。

541 的情况上面的领导们不是不清楚，他们一方面粉饰太平，另一方面，总是幻想着用市场经济的法则去解决计划经济留下的问题。
位于闻喜县的六分指和十分指严重亏损，依照企业法先后进行了破产。
结果破产造成了几千职工和近万名家属生活无以为继，流离失所。
而大大小小的领导却在破产的同时大肆进行暗箱操作，肆意侵吞国有资产。
六分指破产后，原来工厂里存有价值上百万的数控车床，刨床等，还有各个车间的成品库、材料库、废品库，这些库房都有详细的账目，然而这些东西的处理情况，广大职工却毫不知情。
破产破得工人阶级彻底成了无产者，而一些领导们却成了先富起来的成功人士。

541 最后陷入困境的是十七分指，十七分指是 541 的自备电厂。
早在七十年代，十七分指还没投产时，各分指用的都是地方上的电。
由于用电没保障，几个分指都流传着一句话，那就是穷山西烂绛县，不是停水就停电。
十七分指拥有四台 2.5 万千瓦、一台 2.75 万千瓦发电机组，总容量 12.75 万千瓦，
并拥有 110KV、35KV、10KV 变电站各一座及相应的输配电网络，承担着 541 各厂的供电任务，多余的电供国家电网，总资产五亿元左右。

几十年来，十七分指为了支持大山里 541 各厂的生产，耗尽了自己身上所有的能力。
其它分指虽然大都开不了工资，但十七分指的效益一直不错，工资也有保障。
2010 年十七分指被被列入小火电，予以停产，继 541 各分指之后也最终走入了绝境。
明天的早餐在哪里？一千多职工和数千家属开始为明天的生活担忧。
而此时，家属区破旧的单元楼一层的外墙旁，一孩童的信笔涂鸦却让人感到无限感慨。
一简笔大熊猫画像之旁，写着一行稚嫩但却令人心动的粉笔字，“台湾台湾你回来吧！北京把大熊猫都给你了！”

至此， 541 各厂除二分指（铸造业由于环保全国各地限制）效益尚好外，其他各分指几乎奄奄一息。
541 总部也搬离闻喜县东镇了，东镇那只剩下总部大院破旧的楼房和一些老弱病残的退休职工。
划归中信后，总部机关更名为中信机电制造公司，先是以机构精简靠前指挥为由迁往二分指，
后又以交通不便为由在离各分指更远的侯马市买地，盖起了办公楼和宿舍区，
并以补贴的形式把房子卖给公司大大小小的领导，包括各分指的厂级领导，而 541 各分指的十几万职工和家属却被彻底撇在大山里。

== 第八章 兵工二代苦不堪言

上世纪九十年代，作为七十年代首批来到大山里的541兵工战士们已经基本退休，继而成长起来的是当初跟随父母来到这里的兵工二代。
七十年代，父母们来到中条山，岁数大点的孩子，上山下乡，插队到各分指附近的农村里，和他们一起的有来自各地的知情，尤以北京知青居多。
知青返城时，外地的知青回到了他们原来的城市。
而541的知青则回到父母所在的工厂当了工人。岁数小点的，赶上了高考，但那时高考是千军万马过独木桥，能考走的微乎其微。
那些考上大学的应该是第一批离开 541 的人了，他们走了，不会再回来。
剩下的则通过上 541 技校、接班、招工等各种方式，全部进到了 541 各个分指，成为生产一线的主力。
到这时，一代兵工战士献了青春，又真正把子孙奉献了。

上世纪九十年代开始， 541 效益开始下滑，当时风行留职停薪，一些兵工二代离开了 541，开始走出大山，出去打工。
兵工二代从他们的父辈那不仅继承了吃苦耐劳的光荣传统，同时还拥有精湛的技术。
时值珠三角、长三角和山东沿海发展初期，民营企业迅速成长，所以他们出去后也很快在当地有了新的用武之地。

留职停薪不仅要给厂里交钱，同时也有期限。期限到时，有些人不愿回厂了，于是各分指很快便出台文件，让限期返厂，逾期不归者以开除论处。
那时候国有企业职工身份非常重要，于是，大批出去的人回来了，但仍有一些勇于第一个吃螃蟹。
很快，各个厂新的办法出台了，不回来者，本人开除，配偶限期离厂，房子厂里收回，孩子办理离校手续。
一些人回来了，但还是有人回来接上家人，勇敢地走了出去。
再后来，由于外面的企业开始给职工办理档案和各种保险，于是，一批又一批的人为了生活走了出去，
厂区大门的宣传栏里隔三差五地张贴开除职工的通告，只是通告一次比一次开列的名单多。
到后来，竟然有很多厂里的中干，甚至厂干在狠捞一把后也离开了厂。当然，他们的名字也出现在各厂的公示栏里。

1999 年，全国的国企开始推行下岗分流、减员增效。 541 各厂也开始有大批的职工下岗，基本上属于兵工二代那批人。
据国家统计局统计，全国共有三千万国企职工下岗。后来 541 各分指开始对下岗职工进行工龄买断，按照每年工龄买断 500 元的标准，每个人拿到了一万元左右。
下岗买断的地雷阵把 541 成百上千的职工炸得妻离子散，背井离乡，使他们在最为困难的时候，坠向深渊。
据不完全统计， 541 各厂仅在北京打工的人就有一千人之多。
运城和陕西韩城有两趟发往北京的客车，这两趟车在侯马都预留两节车厢。
每当过完年后，车厢里都会有很多外出打工的 541 人。
过去说凭借国际歌，你可以找到组织。
虽然现在由于人员流动，说普通的越来越多了，但是凭他们的年龄，凭借他们兵工厂的普通话你还是会很容易地辨认出来。
你可以大胆地问他是几分指的，放心一般不会问错。

下岗使 541 各厂在人员与技术上彻底伤失了元气。
各分指的车间、处室以下岗为由，借政策的力量，打击报复职工，把平时与其不对付的人都予以下岗。
而各单位凡是能对领导提意见的，大多是技术上有一套的职工。
于是，下岗后一大批技术优秀的职工被迫离开了工厂。
他们不是富余职工，本来就是各单位的中坚力量。
由于效益不好，这些年来，各个分指招不来工人，于是就大量地招收工厂附近的农民，名为协议工。
于是工厂大批的精密设备由于操作不当受到了损坏，同时各种卡具、量具也大批丢失、损坏。
到了割麦子的时候，协议工说不来就不来了，各车间的领导急的象热锅上的蚂蚁。
厂里的正式职工可以不给开工资，但是协议工是必须给开的，而且一天都不敢拖欠。
因为他们都是附近的农民，厂里怕农民来厂里闹事。

兵工二代人到中年，大多都四、五十岁了，上有老，下有小。
父母年轻时从全国各地来到这中条山的 541，如今也都七十多岁的老人了。免费医疗没有了，职工按照比例报销。
各厂的医院由于老大夫退休，新大夫招不来，且设备陈旧，看病都赶不上乡镇的卫生院了。
老兵工们要想看个病不是去几十里外东镇的 541 总医院，就是去侯马、运城等地。
然而，高昂的医药费不仅压弯了这些从不畏惧困难的老兵工的腰，也把兵工二代的腰压弯了。
为了跟厂里借点钱，救父亲的命，有的兵工二代不得已流着泪给厂长下跪。

1999 年后，由于住房体制改革，原来的福利性住房取消，取而代之的货币性住房。
541各分指的家属区都是七十年代建造的，几十年的风雨岁月已经使得各山谷里的楼群十分破旧，八十年代还曾经加固过。
由于年久失修，一到雨季，所有三楼的住户楼顶都要漏水。
家里到处都摆放着各种各样的盆、桶来接水。就是这些房子，发了个房本，说这是你们自己的了，就把房子卖给了职工。

兵工二代的孩子们上学也赶得不是时候，每个大人们都希望自己的孩子好好学习，可当孩子们把大学的录取通知书拿回来时，教育产业化使得这些工资低的可怜，且又长期拖欠的工人们欲哭无泪。
为了供孩子们上学，他们借遍了所有能借到的钱。
他们把自己的生活成本压缩到最低。夏天他们去附近农村的麦地里捡麦子，秋天去给农民打工收玉米。
每次开了工资，给孩子们把生活费寄去使他们最感幸福的时候，同时也是他们最为辛酸的时候。

说起穿戴，曾经的 541 人，引领当地的时尚潮流，现在，老职工们基本上穿的都是以前发的，洗的发白劳保衣服，
二代兵工们总要出门、总得交往，多少还准备一两身看的过眼的衣服，也是反季削价淘回的。
他们渴望交际，却不敢交际，捉襟见肘的收入使他们汗颜，只好蜷缩在筒子楼里与电视作伴。

市场的肉价已经涨到了十几元一斤，鸡蛋也和北京一样 4 块钱一斤了。
几十年前五分钱一斤的西红柿已经涨到了两块，黄瓜三块钱也只能买到两根了。
即便去趟最近的侯马，四十公里的路程，路费也由以前的 9 毛钱涨到了现在的 11 元。
附近的县市快速发展，马路宽敞，高楼林立，而大山里分指却日渐衰败。
在侯马坐车买票时，如果你说去哪个分指，你放心，小偷都不会盯你。541 职工的穷名已经传遍了山西南部各个地方。

家属区旁市场的小贩们也知道分指人很穷，但是他们的生意却受不到太大影响。
有小贩说，谁说分指没钱，那么多肉一上午就卖完。
可是他们不知道，每个分指都有几十甚至几百个先富、甚至暴富的处级干部，否则一个分指几千、甚至几万人，那点肉每个人塞牙缝都不够。
经济绝对是个翘翘板，一部分人的发达绝对是以更多的人贫穷作为其代价。兵工二代们数月不知肉滋味的人大有人在。

== 第九章 窘状成因

541 全线失守不能归咎为市场，九十年代，民营企业还只是处于发展阶段，根本没有实力与具有强大机械加工能力的国家特大型工业企业的 541 抗衡。中信接管了 541，在政治上获得了极大的回报。
但中信毕竟只是些搞金融、弄证券的商人。541 各厂的生产线都是按军品设置的，按照保军转民的要求，军品生产线必须保留，开发民品生产必须建立新的生产线。
而要进行技术改造则需要大量的资金投入。中信起初也为 541 的民品生产线改造注入了大量资金，但后来投资便变得越来越谨慎。
进入 21 世纪后，随着中信大力开拓海外金融市场，对 541 几乎就没什么资金投入了。
找兵器工业部吧，你已经脱离军工系列，国家军工改革脱困的政策也享受不到，至此，541 陷入军不军、民不民，官不官、商不商，姥姥不疼、舅舅不爱的尴尬境地。

541 全线失守，也不能归咎于某任领导、某个厂长，上一章讲的现象，只是个别领导、局部问题，绝大多数领导还是禅精竭虑想把 541、把各分指搞好，无奈手脚束缚、包袱沉重、积重难返。
近几年，国家惠民政策、国有企业改革脱困政策多少也惠及 541 各分指，诸如，学校归地方、离退休工资地方统筹等。
但由于历史、地理原因，企业办社会问题在 541 依然很突出，幼儿园、医院、水、暖、电等基础设施维护、离退休工资统筹外企业补贴等，
举个例子，各分指用于抽取地下水的电费，每个分指每年不少于 20 万元。

541 全线失守也不能归咎地方政府，541 工程从开工建设以来，作为大型兵工企业，从资产到人事始终先后处于装甲兵司令部、五机部、兵器工业总公司、国家机械委的严密监管之下。
划归中信后，中信对 541 的领导只做备案，任其自我发展，对各分指的资产与人事的监管完全流于形式。
地方政府理解、同情 541，却爱莫能助，你是条管、是中央直属企业，对于市、县两级来说，这个包袱它背不动！也不能背！
也只有逢年过节，组织相关部门从人道的角度进行一下慰问。

笔者愚见，541 问题的产生，是国家在特殊年代、特殊历史时期的产物。
广大老一代军工响应国家号召，服从组织安排，为国家建设三线，集体汇聚到这里，
为祖国国防事业献出了自己的青春、毕生和子孙。
现在国家改革开放、跨越转型，他们以前的优势变为劣势，从思想到行为，整整影响三代人，
要他们靠自己、靠企业破旧厂房、设备想要生存，想要翻身？难，难于上青天你！
俗话说的好，解铃还须系铃人，要想根本解决 541 的问题，还是要国家组织相关部门认真调研，广开思路，多渠道加以解决，消除历史遗留问题。
不要让为了祖国三线建设的老军工们流汗、流血、又流泪。要让他们也能享受到国家改革开放的成果，让他们也感受到国家和谐社会和共同富裕的政策。
