= 喜迎山西一建七十华诞

== 企业介绍

山西一建集团有限公司（以下简称山西一建）系中国企业500强山西建设投资集团旗下的核心成员，是集建筑施工、基础设施投资建设运营、房地产开发、建筑工业及物流、设计咨询、建筑劳务、国际经济技术合作、建筑科研、物业服务等业务于一体的大型企业集团。

image::https://mmbiz.qpic.cn/mmbiz_jpg/oiazjZcPwEhz8AaElO33fK7uI8coJoIJl2jMEyAzz3YZ4thRfwESQSbYywW9P88xfOeliaFZJMhe2ktfFIodX53g/640?wx_fmt=jpeg&wxfrom=5&wx_lazy=1&wx_co=1[Image]

首个古建工程鹳雀楼复建工程同时斩获鲁班奖和詹天佑大奖两项大奖，被评为国家级科技示范工程。其中，詹天佑大奖填补了山西空白。

山西一建于1952年始建于北京，由华北党政军机关14个生产单位组建而成，1954年与原中国解放军建筑工程第一师胜利会师，企业发展经历了初战京华、兵工整编、转战南北、三线建设的光辉历程，2012年企业改制为国有控股集团公司，现有职工2800人，下辖分（子）公司70个，拥有建筑施工总承包特级、工程设计建筑行业甲级资质，具备国家商务部批准对外援助成套项目总承包企业资格。近年来，集团主要经济指标以年均两位数速度高速增长，多次荣获山西省优秀骨干建筑企业，2016年跻身中国建筑业成长性200强。

image::https://mmbiz.qpic.cn/mmbiz_png/oiazjZcPwEhz8AaElO33fK7uI8coJoIJlr36pPfTLzLUOT3WCO2wBKnR4aH4nZ3rdG1E62iajhRmQTTibicqK1Z3CA/640?wx_fmt=png&wxfrom=5&wx_lazy=1&wx_co=1[Image]

山西一建紧跟建投集团战略布局，与山西建投集团北京总部和建投国际协同运营，着力开拓华北和海外市场；牵头推进山西建投临汾建筑产业园区建设和运营，传承古建技艺，推广装配建筑，实现绿色建造。集团业务覆盖山西、北京、天津、河北、河南、甘肃、安徽、广东、广西、海南等全国20多个省份，以及几内亚、喀麦隆、斯里兰卡等国际市场，先后建设了一大批国防、工业、民用、市政公用工程、超高层和大跨度建筑，承建工程项目多次荣获鲁班奖、詹天佑大奖、国家优质工程奖、中国装饰工程大奖、中国钢结构金奖、中国安装之星奖，汾水杯、北京长城杯、甘肃飞天奖等国家级和省市级奖项。

image::https://mmbiz.qpic.cn/mmbiz_jpg/oiazjZcPwEhz8AaElO33fK7uI8coJoIJlFvPGplicRH2WicqPcCj1PZVldmYuYBibEdCtjujw7iawYLW7uZaUyh8rng/640?wx_fmt=jpeg&wxfrom=5&wx_lazy=1&wx_co=1[Image]

甘肃省泾川县大云寺博物馆舍利塔工程荣获“国家优质工程奖”、``甘肃飞天奖''

在基础设施投资建设领域：山西一建先后参与了多个四好农村公路PPP项目、城市“煤改电”特许经营项目、标准化厂房PPP项目、智造园区PPP项目的投资、建设和运营，形成了系统的“投、融、建、运”一体化投资管理能力。

古建工程领域：山西一建是中国民族建筑研究会常务理事单位，具备全国领先的古建专业技术和施工建造能力，拥有国家发改委立项的“传统建筑综合施工技术及传统工艺科学化研究平台”，主编了《仿古建筑消耗量定额》和《传统建筑工程技术规范》2项国家标准，拥有4项古建国家工法，承建了楼、塔、庙、院、馆、门等古建工程百余项，为弘扬中华传统文化和传承古建营造技艺贡献一建力量。

image::https://mmbiz.qpic.cn/mmbiz_jpg/oiazjZcPwEhz8AaElO33fK7uI8coJoIJlWQftysnw1OsmuJuVyHZlePdHabwYKIIVb1WngaaYlntqtu4YApntGg/640?wx_fmt=jpeg&wxfrom=5&wx_lazy=1&wx_co=1[Image]

曲村—天马遗址晋侯墓地保护工程  荣获“国家优质工程奖”

新能源领域：山西一建先后在山西岢岚县、繁峙县、隰县、孝义以及河北蔚县、黑龙江鹤岗、广东福海、新疆廉江等地承建光伏EPC总承包项目，积累了数百兆瓦的光伏业绩。

image::https://mmbiz.qpic.cn/mmbiz_jpg/oiazjZcPwEhxM9iabm5cwpem2mCcBcf5OBNeR0iaOgZbkMPUdJuv8IQoG3zHibiaVZYq5UctchzDeObiapSoWTuoUQ8Q/640?wx_fmt=jpeg&wxfrom=5&wx_lazy=1&wx_co=1[Image]

山西临汾新医院门急诊、医技、住院楼工程 荣获“鲁班奖”、``中国安装之星''

国际工程领域：山西一建在海外市场披荆斩棘、稳步前行。在“一带一路”沿线，承建了喀麦隆水厂、堆场项目，斯里兰卡商业广场项目以及几内亚最大的铁路交通项目——马西铁路项目。

山西一建长期致力于建筑科技和施工管理的研究与创新，拥有省级企业技术中心、建筑设计研究院和BIM技术中心及科研检测中心，获评为国家高新技术企业，现有注册结构师、注册建筑师、一级建造师、造价师、高级工程师等高素质人才1000余人。一建人始终秉承“实力建筑、恒久传承”的企业愿景，赓续红色基因、弘扬传承历史文化、传承红色基因、传承军旅作风、传承“两逢”精神、传承家园情结、传承匠心古建、传承光伏速度七方面构成的“传承”文化，不断提升企业核心竞争能力，连续多年荣获全国文明单位、全国优秀施工企业、全国用户满意施工企业、全国建筑业AAA级信用企业等诸多国家级、省级荣誉称号。

回首过去，山西一建积极履行社会责任，既有国防建设的积极投身、广西柳州的忘我奉献，三线建设的光辉印记，也有汶川地震的向险而行，新冠疫情的责任担当、乡村振兴的勇担使命，出色完成的四川都江堰长河村和金藤村援建过渡安置房项目、山西神池方舱隔离点项目、左权泽城村美丽乡村项目等急难险重任务，充分展示了一建人的勇于担当、服务社会的真情大爱。

image::https://mmbiz.qpic.cn/mmbiz_jpg/oiazjZcPwEhz8AaElO33fK7uI8coJoIJl0bQgJNlabMU48PBTa20k3QHTdKoYEbLCZEo4ibzzicvqjY4xCPHmE8Fw/640?wx_fmt=jpeg&wxfrom=5&wx_lazy=1&wx_co=1[Image]

展望未来，山西一建将不忘初心、牢记使命，同国家战略融合、与区域发展同步，围绕“聚焦六新，转型发展”的战略定位，以投资促转型，以合作谋共赢、以务实固基础、以履约筑品牌，着力打造以工程总承包为核心的“投、融、建、运”产业平台，奉献精品、开创未来！

迈向新征程，山西一建以70华诞为新的契机，协同山西建投北京总部和建投国际、
山西建投临汾产业园区一体化经营，集山西建投发展之力，强化集团引领，
大力弘扬执中竞上、恒久传承的企业精神，凝聚发展合力，携手共创一建美好未来，
戮力把山西一建打造成为国际化的大集团公司！

审核：许玉玲
