= 着火公司：山西一建一段几乎被人遗忘的历史
程建民
2022.7.11

山西一建成立至今已有65年了，60多年来公司发展有了太多的经历，但公司新入职的员工对公司60多年的发展历程知之甚少，随着年代的推移，对公司发展历史知道的人越来越少，今天将公司成立之初发生的对公司现在影响较大的一段历史写给大家，由于时间较长，如个别情节有误，希望知情者给予指正。

山西一建1952年由中央华北局振华总公司负责组建，名称为华北基本建设直属第一工程公司，主要完成工程有天安门观礼台、北京体育馆、解放军总医院、南苑机场、清华大学水利馆等。1954年公司调山西大同市与中国人民解放军建筑工程第一师合并，名称变更为建工部华北大同总公司，后来名称多次变更：1958年调广西柳州市名称变更为建工部四局四公司，1962年调山西侯马市名称变更为建工部八局七公司，1978年划归山西省，名称变更为山西省第一建筑工程公司，现名称为山西一建集团有限公司。 

公司成立后承揽的最大的工程之一就是北京体育馆，当时该体育馆的规模为亚洲最大的体育馆，应该说也是国字号的重要工程，贺龙元帅当时是国家体委主任，对北京体育馆建设非常重视，多次去工地视察指导工作。公司当时也是把主要精力放在了北京体育馆建设上，跟现在施工工艺设备相比，当时工艺设备不仅是非常落后，甚至可以说是很原始，没有塔吊、卷扬机等垂直运输设备，施工现场搭的马道（斜坡道），所有的建筑材料包括模板、钢筋、混凝土全是靠人挑肩扛运上去的，混凝土振捣没有振捣器，全靠工人用钢钎插捣，施工条件非常艰苦。但公司参加施工的干部、技术人员和全体工人发扬了不怕苦不怕累的精神，奋战在工地上，以确保体育馆工程按期交工。

为了赶工期，冬天三九严寒天气工地仍继续施工，当时采用暖棚及加热热养护法施工，即梁板柱支模完成后，下部完全封闭，局部空间加热形成暖棚；为了防止浇筑的混凝土上部表面受冻，工地上采用了白灰加锯末的混凝土防冻保温工艺，具体做法就是：浇筑完混凝土后，在混凝土表面覆盖草帘，次日待混凝土终凝后，在草帘下面加铺白灰锯末加温层（事先按一定比例，将过筛后小于1cm的生石灰块与锯末混合均匀，铺在混凝土表面，然后浇水，使生石灰在消化的过程中产生热量，在混凝土中设立测温孔监测混凝土温度），以保持混凝土在一定正温度，从而使混凝土强度继续增长。在体育馆工程接近收尾浇筑混凝土的时候，由于白灰（白灰未按要求过筛，个别白灰块过大）锯末比例不当，造成白灰锯末温度过高，引燃了草帘和木模板，工地发生了火灾，将体育馆工程（由比赛馆、游泳馆和练习馆三个馆组成并用高廊连接）中正在施工的练习馆工程结构部分的草帘和模板烧毁，造成了一场大的安全责任事故，公司领导和全体职工感受到了莫大的内疚和压力，按照安排两个月后体育馆将有重大活动，为了不耽误活动安排，公司领导和全体职工提出了奋战两个月，确保体育馆工程按时交工的口号，公司领导和全体职工不分白天黑夜，吃在工地，住在工地，夜以继日的奋战在工地上，大家克服了三九严寒恶劣天气带来的不利影响，终于保质保量，按期完工，确保了体育馆如期使用。虽然因为着火，但当时公司领导和职工背负压力，迎难而上的精神得到各级领导和大家的赞扬，都纷纷议论，这个公司不简单，着了一把火，还能冒着三九严寒天气，保证工程按时交工，真是能打硬仗，就这样当时公司落下了“着火公司”的名声。

上世纪60年代中期，公司名称变更为建工部八局七公司，在河北邢台承揽了部队的一项保密工程，该工程屋盖设计为预应力屋架，当时国内预应力工程还未普及，部队营建部门不知预应力是怎么回事，认为预应力技术是一项很高深的技术，对公司能否干好这个工程很有疑虑，因此特别着急。当时公司派了综合加工厂李瑞久副厂长带领一个有技术人员及木工、钢筋工、混凝土工等二十余人组成的混合作业队进驻现场，部队营建部门看到就这么几个人，对能否干预应力屋架更持怀疑态度；我们的人进场后简单安排好食宿后，立即开始工作，平整场地，制作模板，加工成型钢筋，浇筑混凝土，一切工作有条不紊地进行着。而且当时采用的是叠合法生产，一套模板成型5榀屋架，即第一榀屋架浇筑后，待强度上来后，立即拆模，并以底下屋架为底模支第二榀屋架侧模，接着浇筑第二榀屋架，以此类推直至第五榀屋架，既节省材料，速度又快，不到三个月就圆满完成预应力屋架制作任务，部队营建部门对此非常惊讶，说在我们看来心里没有一点底，感觉非常艰巨复杂的工程，你们短短两个多月就顺利完成，而且质量非常好，你们公司真是一个施工技术水平高又能打硬仗的公司，给予了公司很高的评价。

后来因战备需要，该工程又迁往四川（即当时的三线建设），该部队提出要公司随他们去四川搞营建，他的上级单位专门派人去当时的国家建工部联系，部里接待部门了解后说“你们说的公司我们知道了，是那个着火公司，我们知道那个公司是一个能打硬仗比较不错的公司，在部里也是能挂上号的一个比较好的公司，但是部里的施工力量是按区域（即东北、华北、西南等区域）配置的，你们去四川，我们部里会给你们安排好的施工力量，这个公司就不要动了，谢绝了部队的要求。

这就是公司当初被人称为“着火公司”的来历及以后因这段经历而发生的一件事，一建公司到现在已成立60余年，公司的老前辈及一代代的员工为公司的发展付出了辛勤的努力，才使得一建这些年发展得越来越强，让我们永远记住他们的付出，让一建公司发展得越来越好。
